# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

segment <- function(argv) {
    invisible(.Call(`_HiCKeyR_segment`, argv))
}

segHeatMap <- function(argv, s = 0L, e = -1L) {
    .Call(`_HiCKeyR_segHeatMap`, argv, s, e)
}

